name: frontend

on:
  push:
    paths:
      - ".github/workflows/frontend.yml"
      - "frontend/**"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: npm run frontend:lint

      - name: Build
        run: npm run frontend:build

      - name: Install 'tree' command
        run: sudo apt-get install tree

      - name: Validate Vue build
        run: tree frontend/dist
